version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  whats-changed:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue.yml
          mapping: |
            service/example/.* build-example true
            service/iam/.* build-iam true
